data<-read.table("Pt_test_E-7_PzVrK.dat")
x<-data$V1
y<-data$V2
err<-data$V3
fx<-function(x,a,b){a/x^b}
ds<-data.frame(x=x,y=y)
fitting<-nls(y~fx(x,a,b),data=ds,start=list(a=.5,b=.5),trace=F)
pdf("E-7.pdf")
plot(x,y)
arrows(x,y-err,x,y+err,length=0.05,angle=90,code=3)
lines(x,predict(fitting),lty=3,lwd=2)
summary(fitting)
dev.off()
